name: hello-world-action
on: push

jobs:
  hello-world-first-job:
    runs-on: ubuntu-latest
    steps:
     - name: check out repository code
       uses: actions/checkout@v4.2.2
    - run: echo "$(cat hello_world.txt)"
    
